[package]
name = "columnar"
version = "0.1.0"
publish = false
authors = ["Moritz Hoffmann <moritz.hoffmann@inf.ethz.ch>"]

[[example]]
name = "columnar"

[features]

default = [ ]

verbose = [ "columnar_derive/verbose" ]

[dependencies]
columnar_derive = { path = "columnar_derive" }

[profile.release]
debug = true

[profile.bench]
debug = true